# Generated by Django 3.2.7 on 2021-11-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='org_id',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='donation',
            name='picture',
            field=models.ImageField(upload_to='donations/'),
        ),
    ]
