# Generated by Django 3.2.7 on 2021-11-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20211115_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationtraits',
            old_name='donation_id',
            new_name='donation',
        ),
        migrations.AlterField(
            model_name='donation',
            name='expiration_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
