# Generated by Django 3.2.7 on 2021-11-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20211116_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
