# Generated by Django 3.2.7 on 2021-11-17 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_alter_organization_url'),
        ('listing', '0004_alter_donation_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('deactivation_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RequestTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.IntegerField(choices=[(0, 'is_cans'), (1, 'is_perishable')])),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.request')),
            ],
        ),
    ]
