# Generated by Django 3.2.7 on 2021-11-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auto_20211106_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
