name: Docker Image CI

on:
  push:
    branches:
    - main
    - features/**
    - test/**
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: sh scripts/start_docker.sh 
